# Generated by Django 5.1.4 on 2024-12-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('about_content', models.TextField(blank=True)),
                ('about_time_create', models.DateTimeField(auto_now=True)),
                ('about_time_update', models.DateTimeField(auto_now_add=True)),
                ('about_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Последние посты',
                'verbose_name_plural': 'Портфолио',
            },
        ),
        migrations.CreateModel(
            name='Contact_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=200)),
                ('contact_content', models.TextField(blank=True)),
                ('contact_time_create', models.DateTimeField(auto_now=True)),
                ('contact_time_update', models.DateTimeField(auto_now_add=True)),
                ('contact_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Последние посты',
                'verbose_name_plural': 'обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Head_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('time_update', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Последние посты',
                'verbose_name_plural': 'Ифориация на главной странице',
            },
        ),
    ]
